// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgeHe8diakO1cGYivlBX5aDUebO4m9KY0',
    appId: '1:1066265820406:web:27dd45b5bcd7b5867d40d7',
    messagingSenderId: '1066265820406',
    projectId: 'simple-chat-app-eb5f6',
    authDomain: 'simple-chat-app-eb5f6.firebaseapp.com',
    storageBucket: 'simple-chat-app-eb5f6.firebasestorage.app',
    measurementId: 'G-J3P7P63JX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL_Tg5bNz0Ap06NwunBBMDVpmU__KYj3E',
    appId: '1:1066265820406:android:ff578e690672c46d7d40d7',
    messagingSenderId: '1066265820406',
    projectId: 'simple-chat-app-eb5f6',
    storageBucket: 'simple-chat-app-eb5f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Yocjkd6IU9hEs8vFtvHChvLu9vzxu7o',
    appId: '1:1066265820406:ios:c3658de6ca990d7a7d40d7',
    messagingSenderId: '1066265820406',
    projectId: 'simple-chat-app-eb5f6',
    storageBucket: 'simple-chat-app-eb5f6.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Yocjkd6IU9hEs8vFtvHChvLu9vzxu7o',
    appId: '1:1066265820406:ios:c3658de6ca990d7a7d40d7',
    messagingSenderId: '1066265820406',
    projectId: 'simple-chat-app-eb5f6',
    storageBucket: 'simple-chat-app-eb5f6.firebasestorage.app',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgeHe8diakO1cGYivlBX5aDUebO4m9KY0',
    appId: '1:1066265820406:web:7015b9642e020b357d40d7',
    messagingSenderId: '1066265820406',
    projectId: 'simple-chat-app-eb5f6',
    authDomain: 'simple-chat-app-eb5f6.firebaseapp.com',
    storageBucket: 'simple-chat-app-eb5f6.firebasestorage.app',
    measurementId: 'G-XWG3E1LWB2',
  );
}
